### ISSUE TITLE
SimianArmy build fails on :test

### ISSUE THREAD

**Issue by 302416** [Netflix/SimianArmy#146]
I just cloned SimianArmy from git://github.com/Netflix/SimianArmy.git today, and try to build it by running ".\gradlew build --info"

But got build failed, 261 tests completed, 5 failed

Here's the exception on the console::test (Thread[main,5,main]) started.
:test
Executing task ':test' (up-to-date check took 0.952 secs) due to:
  No history is available.
Starting process 'Gradle Test Executor 1'. Working directory: D:\SimianArmy\SimianArmy Command: C:\Program Files\Java\jdk1.7.0_71\bin\java.exe -Djava.security.manager=jarjar.org.gradle.process.internal.child.BootstrapSecurityManager -Dfile.encoding=windows-1252 -ea -cp C:\Users\fengqh\.gradle\caches\1.12\workerMain\gradle-worker.jar jarjar.org.gradle.process.internal.launcher.GradleWorkerMain
Successfully started process 'Gradle Test Executor 1'
Gradle Test Executor 1 started executing tests.
2014-10-29 20:46:18.262 - ERROR AbstractJanitor - [AbstractJanitor.java:298] Failed to clean up the resource 11.
java.lang.RuntimeException: Magic number of id.
        at com.netflix.simianarmy.janitor.TestAbstractJanitor.cleanup(TestAbstractJanitor.java:81)
        at com.netflix.simianarmy.janitor.AbstractJanitor.cleanupResources(AbstractJanitor.java:293)
        at com.netflix.simianarmy.janitor.TestAbstractJanitor.testJanitorWithCleanupFailure(TestAbstractJanitor.java:223)

**Comment by ebukoski** [comment]
Closing as duplicate.  See #155 for updates.
