### ISSUE TITLE
Error making SSH connection to instance

### ISSUE THREAD

**Issue by mrdlmndr** [Netflix/SimianArmy#168]
When I enable the other options like burncpu, which require SSH to instance. They are giving below error:
2015-01-16 04:54:55.177 - WARN  ChaosInstance - [ChaosInstance.java:105] Error making SSH connection to instance
com.google.inject.CreationException: Guice creation errors:

1) org.jclouds.rest.config.SyncToAsyncHttpApiProvider<org.jclouds.rest.HttpClient, A> cannot be used as a key; It is not fully specified.

2) org.jclouds.rest.config.SyncToAsyncHttpApiProvider<org.jclouds.ec2.EC2Client, A> cannot be used as a key; It is not fully specified.

3) org.jclouds.rest.RestContext<org.jclouds.ec2.EC2Client, A> cannot be used as a key; It is not fully specified.

4) No implementation for org.jclouds.rest.HttpClient was bound.
  at org.jclouds.rest.config.BinderUtils.bindHttpApiProvider(BinderUtils.java:109)

5) No implementation for org.jclouds.ec2.EC2Client was bound.
  at org.jclouds.rest.config.BinderUtils.bindHttpApiProvider(BinderUtils.java:109)

5 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:407)
	at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:331)
	at org.jclouds.ContextBuilder.buildView(ContextBuilder.java:622)
	at org.jclouds.ContextBuilder.buildView(ContextBuilder.java:602)
	at com.netflix.simianarmy.client.aws.AWSClient.getJcloudsComputeService(AWSClient.java:728)
	at com.netflix.simianarmy.client.aws.AWSClient.connectSsh(AWSClient.java:746)
	at com.netflix.simianarmy.chaos.ChaosInstance.connectSsh(ChaosInstance.java:123)
	at com.netflix.simianarmy.chaos.ChaosInstance.canConnectSsh(ChaosInstance.java:101)
	at com.netflix.simianarmy.chaos.ScriptChaosType.canApply(ScriptChaosType.java:61)
	at com.netflix.simianarmy.basic.chaos.BasicChaosMonkey.pickChaosType(BasicChaosMonkey.java:141)
	at com.netflix.simianarmy.basic.chaos.BasicChaosMonkey.doMonkeyBusiness(BasicChaosMonkey.java:121)
	at com.netflix.simianarmy.Monkey.run(Monkey.java:134)
	at com.netflix.simianarmy.Monkey$1.run(Monkey.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

* Can you please help. I already gave the ssh keypath and ssh user in chaos.properties file
     
     simianarmy.chaos.ssh.user = root
     simianarmy.chaos.ssh.key = ~/Mridul.pem

**Thanks in Advance**

**Comment by Narendraalluri** [comment]
I am having this issue now, did you ever find a fix for this?

**Comment by Narendraalluri** [comment]
Changing the guava version in build.grade seems to have fixed the issue

compile 'com.google.guava:guava:16.0.2'

**Comment by ambikanair1990** [comment]
I face similar issue. Below is the error that I get. Tried to change guava version as mentioned in above comment. Chaos Monkey itself did not execute due to the version change. Is there any thing else that I have to focus on. 

2015-03-27 04:03:46.952 - INFO  BasicChaosInstanceSelector - [BasicChaosInstanceSelector.java:65] Randomly selecting 0 from 13 instances, excluding a7cedc82-cd82-45f6-893b-f0533a21e6cb
2015-03-27 04:08:52.963 - WARN  ChaosInstance - [ChaosInstance.java:105] Error making SSH connection to instance
org.jclouds.ssh.SshException: (root:rsa[fingerprint(13:26:62:39:49:1e:09:ea:18:52:f0:af:6e:da:0c:67),sha1(27:0c:56:9b:c9:e2:79:cb:d8:4a:a7:db:c0:7c:38:40:d8:95:04:f7)]@192.168.3.42:22) (root:rsa[fingerprint(13:26:62:39:49:1e:09:ea:18:52:f0:af:6e:da:0c:67),sha1(27:0c:56:9b:c9:e2:79:cb:d8:4a:a7:db:c0:7c:38:40:d8:95:04:f7)]@192.168.3.42:22) error acquiring {hostAndPort=192.168.3.42:22, loginUser=root, connectTimeout=60000, sessionTimeout=60000}: timeout: socket is not established
	at org.jclouds.ssh.jsch.JschSshClient.propagate(JschSshClient.java:333)
	at org.jclouds.ssh.jsch.JschSshClient.acquire(JschSshClient.java:184)
	at org.jclouds.ssh.jsch.JschSshClient.connect(JschSshClient.java:197)
	at com.netflix.simianarmy.client.openstack.OpenstackClient.connectSsh(OpenstackClient.java:480)
	at com.netflix.simianarmy.chaos.ChaosInstance.connectSsh(ChaosInstance.java:123)
	at com.netflix.simianarmy.chaos.ChaosInstance.canConnectSsh(ChaosInstance.java:101)
	at com.netflix.simianarmy.chaos.ScriptChaosType.canApply(ScriptChaosType.java:61)
	at com.netflix.simianarmy.basic.chaos.BasicChaosMonkey.pickChaosType(BasicChaosMonkey.java:146)
	at com.netflix.simianarmy.basic.chaos.BasicChaosMonkey.doMonkeyBusiness(BasicChaosMonkey.java:126)
	at com.netflix.simianarmy.Monkey.run(Monkey.java:134)
	at com.netflix.simianarmy.Monkey$1.run(Monkey.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:389)
	at com.jcraft.jsch.Session.connect(Session.java:194)
	at org.jclouds.ssh.jsch.SessionConnection.create(SessionConnection.java:176)
	at org.jclouds.ssh.jsch.SessionConnection.create(SessionConnection.java:40)
	at org.jclouds.ssh.jsch.JschSshClient.acquire(JschSshClient.java:177)
	... 16 more
2015-03-27 04:08:52.971 - WARN  ScriptChaosType - [ScriptChaosType.java:62] Strategy disabled because SSH credentials failed
2015-03-27 04:08:52.971 - WARN  BasicChaosMonkey - [BasicChaosMonkey.java:129] No chaos type was applicable to the instance: a7cedc82-cd82-45f6-893b-f0533a21e6cb
2015-03-27 04:08:52.972 - INFO  Monkey - [Monkey.java:138] Reporting what I did...

**Comment by Narendraalluri** [comment]
{hostAndPort=192.168.3.42:22, loginUser=root, connectTimeout=60000, sessionTimeout=60000}

From the above line in the stack trace, it looks like the firewall/security issue. Were you able to ssh to 192.168.3.42 manually from the Chaos monkey box? You could also try 'telnet 192.168.3.42 22' and see if the port is accessible.

**Comment by ambikanair1990** [comment]
Hello Sir,

Yes you are right. I am not able to ssh to the above ip. I had to make a small code change.

you will need to change getPrivateAddesses() to getPublicAddresses() in src/main/java/com/netflix/simianarmy/client/openstack/OpenstackClient.java
Line 478 should look like this:
node.getPublicAddresses().toArray()[0].toString(),

Thanks for the quick reply!!

**Comment by apjaffe** [comment]
Switching to JDK 1.7.0_17 instead of 1.7.0_55 fixed this for me.
