### ISSUE TITLE
java.lang.NullPointerException on BasicJanitorRuleEngine.java:76 with a leashed janitor monkey

### ISSUE THREAD

**Issue by lantrix** [Netflix/SimianArmy#189]
I've been running Simian Army, specifically janitor monkey, Leashed.

I get the following
```
java.lang.NullPointerException
	at java.util.Date.getMillisOf(Date.java:956)
	at java.util.Date.after(Date.java:929)
	at com.netflix.simianarmy.basic.janitor.BasicJanitorRuleEngine.isValid(BasicJanitorRuleEngine.java:76)
	at com.netflix.simianarmy.janitor.AbstractJanitor.markResources(AbstractJanitor.java:209)
	at com.netflix.simianarmy.basic.janitor.BasicJanitorMonkey.doMonkeyBusiness(BasicJanitorMonkey.java:95)
	at com.netflix.simianarmy.Monkey.run(Monkey.java:134)
	at com.netflix.simianarmy.Monkey$1.run(Monkey.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

From what I understand, `BasicJanitorRuleEngine.java:76` ends up with the java.lang.NullPointerException due to the fact that the  `clone.getExpectedTerminationTime()` is null because there have been no successful un-leashed runs of Janitor Monkey.

![screenshot 2015-05-08 15 32 51](https://cloud.githubusercontent.com/assets/117008/7531072/85f6f2a4-f597-11e4-93f2-4178087d40a5.png)

Will need to make this code handle null values better, as `java.util.Date.after` can't handle comparing to a null date.

**Comment by ebukoski** [comment]
This was addressed with PR #191
