### ISSUE TITLE
Dependency version conflict

### ISSUE THREAD

**Issue by algra** [Netflix/SimianArmy#246]
We are trying to run a simian army, but not exactly using the way described in the quick start guide (./gradlew jettyRun). We're trying to build simian army as single artefact (simianarmy-x.y.z.war) and then deploy it as a binary artefact to an instance and run it with jetty with our own configs afterwards.

Took latest jetty-runner-9.3.7.v20160115.jar, tried to start it with our own configs located in ./config folder:

```
java \
 -Dchaos.properties=/as24_chaos.properties \ 
 -Dclient.properties=/as24_client.properties \ 
 -Dconformity.properties=/as24_conformity.properties \ 
 -Djanitor.properties=/as24_janitor.properties \ 
 -Dlog4j.properties=/as24_log4j.properties \ 
 -Dsimianarmy.properties=/as24_simianarmy.properties \ 
 -DvolumeTagging.properties=/as24_volumeTagging.properties \ 
 -jar jetty-runner-9.3.7.v20160115.jar \ 
 --classes config \
 simianarmy-2.5.0.war
```

It starts, loads our configs (we can see our settings as simian army prints it), start doing something, like adding monkeys, lists our ASGs, but afterwards throws an exception, I assume it happened while jetty is trying to provide simian army over HTTP:

```
2016-03-10 12:33:34.780:INFO:oejs.ServerConnector:main: Started ServerConnector@1f892cc2{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Exception in thread "main" java.lang.IllegalAccessError: tried to access method com.sun.jersey.core.reflection.ReflectionHelper.getContextClassLoader()Ljava/lang/ClassLoader; from class com.sun.jersey.spi.scanning.AnnotationScannerListener
    at com.sun.jersey.spi.scanning.AnnotationScannerListener.<init>(AnnotationScannerListener.java:89)
    at com.sun.jersey.spi.scanning.PathProviderScannerListener.<init>(PathProviderScannerListener.java:59)
    at com.sun.jersey.api.core.ScanningResourceConfig.init(ScanningResourceConfig.java:79)
    at com.sun.jersey.api.core.PackagesResourceConfig.init(PackagesResourceConfig.java:104)
    at com.sun.jersey.api.core.PackagesResourceConfig.<init>(PackagesResourceConfig.java:78)
    at com.sun.jersey.api.core.PackagesResourceConfig.<init>(PackagesResourceConfig.java:89)
    at com.sun.jersey.spi.container.servlet.WebComponent.createResourceConfig(WebComponent.java:700)
    at com.sun.jersey.spi.container.servlet.WebComponent.createResourceConfig(WebComponent.java:678)
    at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:203)
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373)
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556)
    at javax.servlet.GenericServlet.init(GenericServlet.java:244)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:640)
    at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:419)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:875)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:350)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1379)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1341)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:263)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:405)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:372)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.runner.Runner.run(Runner.java:502)
    at org.eclipse.jetty.runner.Runner.main(Runner.java:547)
```

Same happening while running it with Tomcat 8.0.32.

Not digging very deep, we found out that putting jersey-bundle-x.yy.jar of the same version with other jersey jars as a dependency solves the problem and simian army runs with jetty-runner as well as with Tomcat.

Created this issue just to trace the problem, pull request solving the problem the way described above will follow asap.

**Comment by algra** [comment]
First try was kind of no-brainer and did not actually worked well. Now, after more investigations, I think I finally understood what was happening.

eureka-client 1.4.1 is dependent on jersey-client, -core and apache-client4, but in version 1.19.
simianarmy is dependent on jersey-core and -servlet, but in version 1.11.

As result, some of jersey modules were 1.19, some - 1.11 and it seems that were were conflicts between these two versions. Now it works fine, another [working] PR is on the way.

Why throwing jersey-bundle in classpath solved problem on my Mac laptop, but not on Linux is different behaviour of classloader / order of loading of modules, which resulted that on Mac classes were loaded from bundle, but on Linux - from other modules.
