### ISSUE TITLE
Exception while running the SimianArmy

### ISSUE THREAD

**Issue by agrotarun** [Netflix/SimianArmy#270]
Getting the following exception on running the Chaos Monkey
    
2016-08-17 22:55:21.851 - ERROR Monkey$1 - [Monkey.java:157] CONFORMITY Monkey Error: 
com.amazonaws.AmazonClientException: Unable to unmarshall response (ParseError at [row,col]:[26961,34]
Message: Read timed out). Response Code: 200, Response Text: OK
	at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:1090)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:724)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:11779)
	at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:5905)
	at com.netflix.simianarmy.client.aws.AWSClient.describeInstances(AWSClient.java:470)
	at com.netflix.simianarmy.aws.conformity.crawler.AWSClusterCrawler.clusters(AWSClusterCrawler.java:120)
	at com.netflix.simianarmy.basic.conformity.BasicConformityMonkey.doMonkeyBusiness(BasicConformityMonkey.java:120)
	at com.netflix.simianarmy.Monkey.run(Monkey.java:134)
	at com.netflix.simianarmy.Monkey$1.run(Monkey.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[26961,34]
Message: Read timed out
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:591)
	at com.sun.xml.internal.stream.XMLEventReaderImpl.peek(XMLEventReaderImpl.java:276)
	at com.amazonaws.transform.StaxUnmarshallerContext.nextEvent(StaxUnmarshallerContext.java:207)
	at com.amazonaws.services.ec2.model.transform.EbsInstanceBlockDeviceStaxUnmarshaller.unmarshall(EbsInstanceBlockDeviceStaxUnmarshaller.java:42)
	at com.amazonaws.services.ec2.model.transform.InstanceBlockDeviceMappingStaxUnmarshaller.unmarshall(InstanceBlockDeviceMappingStaxUnmarshaller.java:51)
	at com.amazonaws.services.ec2.model.transform.InstanceStaxUnmarshaller.unmarshall(InstanceStaxUnmarshaller.java:143)
	at com.amazonaws.services.ec2.model.transform.ReservationStaxUnmarshaller.unmarshall(ReservationStaxUnmarshaller.java:67)
	at com.amazonaws.services.ec2.model.transform.DescribeInstancesResultStaxUnmarshaller.unmarshall(DescribeInstancesResultStaxUnmarshaller.java:47)
	at com.amazonaws.services.ec2.model.transform.DescribeInstancesResultStaxUnmarshaller.unmarshall(DescribeInstancesResultStaxUnmarshaller.java:32)
	at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:99)
	at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:42)
	at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:1050)

**Comment by agrotarun** [comment]
The issue came due to some aws timeout issues. Its not coming now. Hence closing it
